# .streamlit/secrets.toml

GEMINI_API_KEY = "AIzaSyBXE6uUViHu50XJoRbzRy3Vkpwtn5J1SpU"


[postgres]
PG_HOST="db.rneoikxngwhhijzzurxa.supabase.co"

PG_PORT = 5432
PG_DB = "postgres"
PG_USER = "postgres"
PG_PASSWORD = "2060"
