# .streamlit/secrets.toml

GEMINI_API_KEY = "AIzaSyCvLF8WJtea9QDFS9KHIrgWPI46wIzZf2g"


[postgres]
PG_HOST="db.rneoikxngwhhijzzurxa.supabase.co"

PG_PORT = 5432
PG_DB = "postgres"
PG_USER = "postgres"
PG_PASSWORD = "2060"
