# .streamlit/secrets.toml

GEMINI_API_KEY = "AIzaSyCK8xBD0VDtnNH9ZkhBLEMheLdI3sF_P84"
[postgres]
PG_HOST="db.rneoikxngwhhijzzurxa.supabase.co:5432/postgres"

PG_PORT = 5432
PG_DB = "Job"
PG_USER = "postgres"
PG_PASSWORD = "2060"
